<h1><?php echo $this->translate('Reset Password'); ?></h1>

<div class="col-sm-12 col-md-12">
    <ul>
        <?php if (isset($this->errorMessages)) : ?>
            <?php foreach ($this->errorMessages as $element => $messages) : ?>
                <?php foreach ($messages as $message) : ?>
                    <li><?php echo $message ?></li>
                <?php endforeach ?>
            <?php endforeach ?>
        <?php endif ?>
    </ul>
</div>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->flashMessenger()->render('request-reset-password-error', ['alert', 'alert-dismissible', 'alert-danger']) ?>
    <?php echo $this->flashMessenger()->render('request-reset-password-success', ['alert', 'alert-dismissible', 'alert-success']) ?>
    <label for="email">Email address</label>
    <div class="input-group">
        <span class="input-group-addon">@</span>
        <?php
        $email = $form->get('email');
        $email->setAttribute('id', 'email');
        echo $this->formInput($email);
        ?>
   </div>
</div>
<?php
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-success');
echo $this->formButton($submit);
echo $this->form()->closeTag();
?>