<h1>Request Reset Password</h1>

<?php echo $this->flashMessenger()->render('request-reset-password-success', ['alert', 'alert-dismissible', 'alert-success']) ?>

<div>
    <p>
        Reset password link has been sent to your email. Please check your email<br />
        <br>
        Click here for 
        <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Login'); ?></a>
        to Dashboard.
    </p>
</div>
