<h1><?php echo $this->translate('Create New Password'); ?></h1>

<div class="col-sm-12 col-md-12">
    <ul>
        <?php if (isset($this->errorMessages)) : ?>
            <?php foreach ($this->errorMessages as $element => $messages) : ?>
                <?php foreach ($messages as $message) : ?>
                    <li><?php echo $message ?></li>
                <?php endforeach ?>
            <?php endforeach ?>
        <?php endif ?>
    </ul>
</div>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
echo $this->form()->openTag($form);
?>

<?php echo $this->flashMessenger()->render('reset-password-error', ['alert', 'alert-dismissible', 'alert-danger']) ?>
<div class="form-group">
    <label for="pwd">Password</label>
    <div class="input-group">
        <?php
        $pwd = $form->get('pwd');
        $pwd->setAttribute('id', 'pwd');
        echo $this->formInput($pwd);
        ?>
   </div>
</div>
<div class="form-group">
    <label for="repwd">Re-Type Password</label>
    <div class="input-group">
        <?php
        $repwd = $form->get('repwd');
        $repwd->setAttribute('id', 'repwd');
        echo $this->formInput($repwd);
        ?>
   </div>
</div>
<?php
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-success');
echo $this->formButton($submit);
echo $this->form()->closeTag();
?>