<h1><?php echo $this->translate('Sign In'); ?></h1>

<?php echo $this->flashMessenger()->render('reset-password-success', ['alert', 'alert-dismissible', 'alert-success']) ?>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

<a href="<?php echo $this->url('zfcuser/request_reset_password') ?>"><?php echo $this->translate('Reset Password'); ?></a>
<br />

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
