<?php

function displayElements($formElements) {
    if (empty($formElements)) {
        return '';
    }
    $output = '<table>';
    foreach ($formElements as $elementHtml) {
        $output .= "<tr><td>$elementHtml</td></tr>";
    }
    $output .= '</table>';
    return $output;
}

?>

<div class="jumbotron">
    <h1>Spreadsheet Generator</span></h1>

    <p>
        This section is for generating spreadsheets of data already stored in the database.
    </p>

</div>

<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Search for Products </h3>
            </div>
            <div class="panel-body">
                <form action="/download/prices-to-update" method="post" >
                <p>
                    <?= displayElements(array_merge($dropDowns, $checkboxes)) ?>
                </p>

                <p><input type="submit" class="btn btn-success pull-right" value="Get Spreadsheet"></p>
                </form>
            </div>
        </div>
    </div>

</div>
