<?php

function buildLinkString($links)
{
    $output = '<table border="0" >';
    foreach ($links as $label => $url) {
        $output .= '<tr><td><a href="' . $url . '" >' . $label . '</a></td></tr>';
    }

    $output .= "</table>";
    return $output;
}

function buildScriptRunString($recentScriptRunData)
{
    $output = '<table border="0" >';
    foreach ($recentScriptRunData as $run) {
        $output .= "<tr>";
        foreach ($run as $label => $value) {
            if ($label == 'script_error_message') {
                continue;
            }
            $output .= '<td>' . $value . '</td>';
        }
        $output .= "</tr>";
    }
    $output .= "</table>";
    return $output;
}


?>

<div class="jumbotron">
    <h1>Welcome to the Repricer Project</span></h1>

    <p>
        This is a project by Andrew Stokinger written for Near Mint Games, using Zend Framework 3
    </p>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Manually Run Scripts: </h3>
            </div>
            <div class="panel-body">
                <p>
                    If you need to run the scripts at off times, or because something needs updated, please click the links below.
                    They will take quite a while to run, please don't close your browser.
                    <?= buildLinkString($scripts) ?>
                </p>
                <!--             <p><a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">ZF Development Portal &raquo;</a></p> -->
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Download Pricing Files : </h3>
            </div>
            <div class="panel-body">
                <p>
                    <?= buildLinkString($downloads) ?>
                </p>

       <!--         <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Explore ZF Modules &raquo;</a></p> -->
            </div>
        </div>
    </div>
</div>
<div class="row">
    <?= buildScriptRunString($recentScriptRunData) ?>
</div>